### ISSUE TITLE
Occasional error when closing modal

### ISSUE THREAD

**Issue by ITninja04** [Blazored/Modal#23]
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Components.CascadingValue1.Microsoft.AspNetCore.Components.ICascadingValueComponent.Unsubscribe(ComponentState subscriber)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RemoveCascadingParameterSubscriptions()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.DisposeInBatch(RenderBatchBuilder batchBuilder)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()`

I'm working on an app that utilizes your Modal, and frequently when closing the modal I get the above error message.

This occurs if I am listening for an onclose event or not, and also happens when I pass parameters or don't. Basically it can happen at any time. I was able to track it down to the 'StateHasChanged' event that gets fired in the CloseModal method.

**Comment by chrissainty** [comment]
Thanks for reporting this @ITninja04, could you put a repo with minimal steps to produce the error?

**Comment by chrissainty** [comment]
I can’t manage to replicate this issue and without any repro steps I’m going to go ahead and close it. Please re-open if you encounter the issue again.
