### ISSUE TITLE
Exception when using Blazor with identity example

### ISSUE THREAD

**Issue by mehmetilker** [Blazored/Modal#290]
**Describe the bug**

I have followed basic example from https://github.com/Blazored/Modal and implemented required parts of example.
When I run the project I am getting following exception:
~~~
InvalidOperationException: Authorization requires a cascading parameter of type Task<AuthenticationState>. Consider using CascadingAuthenticationState to supply this.
~~~

I have realized CascadingBlazoredModal part in App.razor is different from example project here:
https://github.com/Blazored/Modal/blob/main/samples/BlazorServer/App.razor

When I replace it I can run project but getting exception in related page (the page there is open modal button):
Complete app.razor content:
~~~
<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayout)">
                <p>Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>
</CascadingAuthenticationState>

<CascadingBlazoredModal>
    <Router AppAssembly="@typeof(Program).Assembly">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        </Found>
        <NotFound>
            <CascadingAuthenticationState>
                <LayoutView Layout="@typeof(MainLayout)">
                    <p>Sorry, there's nothing at this address.</p>
                </LayoutView>
            </CascadingAuthenticationState>
        </NotFound>
    </Router>
</CascadingBlazoredModal>
~~~

Exception:

~~~
Error: System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Project.XService.GetUndefinedEntitites(String label) in Proejct\Data\XService.cs:line 35
   at Project.UndefinedList.OnParametersSetAsync() in Project\Pages\Entity\UndefinedList.razor.cs:line 42
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
e.log @ blazor.server.js:19
blazor.s
~~~

**Expected behavior**
Open the Modal.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Comment by larsk2009** [comment]
I am not sure from your post, but have you tried this as the whole app.razor?

```cshtml
<CascadingBlazoredModal>
  <CascadingAuthenticationState>
      <Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true">
          <Found Context="routeData">
              <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
          </Found>
          <NotFound>
              <LayoutView Layout="@typeof(MainLayout)">
                  <p>Sorry, there's nothing at this address.</p>
              </LayoutView>
          </NotFound>
      </Router>
  </CascadingAuthenticationState>
</CascadingBlazoredModal>
```

Having 2 separate routers like that is not going to work I think. Let me know if the above works for you!

**Comment by mehmetilker** [comment]
Thanks @larsk2009 it worked.

I tought CascadingAuthenticationState in app.razor coming from default template is related with identity and it should be there. And CascadingBlazoredModal is another thing and should be added not replaced with CascadingAuthenticationState.
