### ISSUE TITLE
[Bug] DotNet 6 migration

### ISSUE THREAD

**Issue by LoupaLoupa** [Blazored/Modal#357]
**Describe the bug**
Trying to migrate application to dotnet 6, I have 2 situation:

1) One of my app give me a yellow triangle and a message NETSDK1082	There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'. But I am not sure this is from Blazored Modal.

So I did

2) Create a minimal version of a pop-up and tried to use Blazored Modal. All compiles and build, but on execution modal.Show<MyClass> dies silently. If I use a link to reach MyClass, it opens as expected.

I understand Blazored Modal might not be .net 6 ready, but I have nothing clearly indicating anything,

Thanks for the help

**To Reproduce**
Migrate to .net 6

**Expected behavior**
Should load and work as expected

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**

 - Blazor WebAssembly

**Additional context**

**Comment by LoupaLoupa** [comment]
Hi,  I have double check all the places we need to put references to so that it works, and I was missing a reference, which explains the dead silence. Once I fix it, I was able to get a stack. Here it goes

`blazor.webassembly.js:1 
 Unhandled Exception:
blazor.webassembly.js:1 
 Microsoft.JSInterop.JSException: Could not find 'BlazoredModal.activateScrollLock' ('BlazoredModal' was undefined).
blazor.webassembly.js:1 
 Error: Could not find 'BlazoredModal.activateScrollLock' ('BlazoredModal' was undefined).
blazor.webassembly.js:1 
     at https://localhost:7231/_framework/blazor.webassembly.js:1:328
blazor.webassembly.js:1 
     at Array.forEach (<anonymous>)
blazor.webassembly.js:1 
     at a.findFunction (https://localhost:7231/_framework/blazor.webassembly.js:1:296)
blazor.webassembly.js:1 
     at _ (https://localhost:7231/_framework/blazor.webassembly.js:1:2437)
blazor.webassembly.js:1 
     at https://localhost:7231/_framework/blazor.webassembly.js:1:3325
blazor.webassembly.js:1 
     at new Promise (<anonymous>)
blazor.webassembly.js:1 
     at Object.beginInvokeJSFromDotNet (https://localhost:7231/_framework/blazor.webassembly.js:1:3306)
blazor.webassembly.js:1 
     at Object.Rt [as invokeJSFromDotNet] (https://localhost:7231/_framework/blazor.webassembly.js:1:59738)
blazor.webassembly.js:1 
     at _mono_wasm_invoke_js_blazor (https://localhost:7231/_framework/dotnet.6.0.0.tj42mwroj7.js:1:193780)
blazor.webassembly.js:1 
     at wasm://wasm/00945abe:wasm-function[2588]:0x8065b
blazor.webassembly.js:1 
    at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
blazor.webassembly.js:1 
    at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
blazor.webassembly.js:1 
    at Blazored.Modal.BlazoredModal.Update(ModalReference modalReference)
blazor.webassembly.js:1 
    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_1(Object state)
blazor.webassembly.js:1 
    at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
blazor.webassembly.js:1 
    at System.Threading.ThreadPoolWorkQueue.Dispatch()
blazor.webassembly.js:1 
    at System.Threading.ThreadPool.Callback()
blazor.webassembly.js:1 
 ThreadPool Callback threw an unhandled exception of type Microsoft.JSInterop.JSException`

Hope this help, thanks for any feedback you can provide :)

Many thanks, Cheers!

**Comment by larsk2009** [comment]
I don't think we have done any work or checked this works with .NET6. I'll make an issue to track .NET6 testing/integration.

**Comment by larsk2009** [comment]
Ah good that it works now, it seems you saw #359? To me it seems this library should work with .net6, at least after merging that PR.

**Comment by LoupaLoupa** [comment]
Yes, I did, which kind of made me want to push my investigation further since all you did was upgrade packages, so it meant it should work.
