### ISSUE TITLE
[Bug] "A Task was Canceled" Exception

### ISSUE THREAD

**Issue by TravisNorwood** [Blazored/Modal#388]
The JavaScript calls in BlazoredModal will sometimes get the below exceptions. We've haven't found a way to replicate, but we think it may have to do with the JS being called after the page is no longer being displayed. Since the JS calls are not critical it would be good to either have a way to configure them not to be done, or wrap them with exception handling that doesn't throw the exception back, causing problems for the application.

Exception:A task was canceled.
Stack Trace:   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Blazored.Modal.BlazoredModal.Update(ModalReference modalReference)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)

**Comment by chrissainty** [comment]
Hi @TravisNorwood, thanks for raising this. 

I'm currently working on the next version of the modal and I'm going to remove all the JS and replace with a native Blazor solution. I'll link this ticket to the PR once I'm at that point.
