### ISSUE TITLE
Blazor Server - TaskCanceledException causes unhandled exception and crashes entire process

### ISSUE THREAD

**Issue by craigajohnson** [Blazored/Modal#390]
Not sure yet what caused this within the app, but we caught this in our IIS logs:

Application: w3wp.exe
CoreCLR Version: 6.0.222.6406
.NET Version: 6.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Threading.Tasks.TaskCanceledException: A task was canceled.
at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
at Blazored.Modal.BlazoredModal.Update(ModalReference modalReference)
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
at System.Threading.QueueUserWorkItemCallback.Execute()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

I think I read that any unhandled JSInterop and/or async void will barf out the process.

**Comment by chrissainty** [comment]
Thanks for raising this @craigajohnson. In the new preview version I've removed the need for JavaScript so this should no longer be an issue. Based on that, I'm going to close this.
