### ISSUE TITLE
[Bug] Unexpected token . at Microsoft.JSInterop.JSRuntime

### ISSUE THREAD

**Issue by JimGeersinga** [Blazored/Modal#581]
**Describe the bug**
Unexpected token . in Blazor Webview I'm encountering a SyntaxError: Unexpected token . in my Blazor Webview application. The error details are as follows:

```lua
blazor.webview.js:1 Unexpected token .
SyntaxError: Unexpected token .
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Blazored.Modal.BlazoredModal.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
NotifyUnhandledException @ blazor.webview.js:1
```

**To Reproduce**
1. Create new .NET MAUI Hybrid  project
2. Add Blazored.Modal to the project
3. Add `CascadingBlazoredModal` around the router as mentioned in the documentation
4. Start app in android emulator.

**Expected behavior**
App starts normally without any errors and I am able to show a modal after button click

**Screenshots**
![image](https://github.com/Blazored/Modal/assets/7780260/79b2a655-10d9-48b6-9dd8-82cfe1e74371)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - MAUI Blazor Hybrid

**Additional context**

This is how my Routes.Razor looks like
```razor
@using Blazored.Modal

<CascadingBlazoredModal>
    <Router AppAssembly="@typeof(MauiProgram).Assembly">
        <Found Context="routeData">
            <RouteView RouteData="@routeData" DefaultLayout="@typeof(Layout.MainLayout)" />
            <FocusOnNavigate RouteData="@routeData" Selector="h1" />
        </Found>
    </Router>
</CascadingBlazoredModal>
```

I have tracked down the interop call location to [this line in Blazored.Modal](https://github.com/Blazored/Modal/blob/92db30baaf607c8a8a8ac35199402280ed80927a/src/Blazored.Modal/BlazoredModal.razor#L70).

Looking at another (microsoft) [component named QuickGrid](https://github.com/dotnet/aspnetcore/blob/1bbf3116889240f5d2668bd42b7284e2999e2ee1/src/Components/QuickGrid/Microsoft.AspNetCore.Components.QuickGrid/src/QuickGrid.razor.cs#L203) I see that there is not really a difference.

**Comment by JimGeersinga** [comment]
With further looking into the problem it seems the `?` in `const overflowState = document.body?.style.overflow;` is the problem.
I created a pull request to resolve this issue.
